version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: backlinio-postgres
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: strapi
      POSTGRES_DB: strapi
    volumes:
      - "backlinio-postgres:/var/lib/postgresql/data"

volumes:
  backlinio-postgres:
    name: backlinio-postgres
